language: go

go:
  - 1.6
  - 1.7
  - tip

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go install github.com/onsi/ginkgo/ginkgo

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
